######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 9 08:08:20 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += Gui
# Input
SOURCES += qbutton.cpp
