######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 9 07:43:05 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT       += core gui
# Input
SOURCES += qedit.cpp
